//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"mime/multipart"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for DocumentStatus.
const (
	DocumentStatusFailed     DocumentStatus = "failed"
	DocumentStatusPending    DocumentStatus = "pending"
	DocumentStatusProcessing DocumentStatus = "processing"
	DocumentStatusReady      DocumentStatus = "ready"
)

// Valid indicates whether the value is a known member of the DocumentStatus enum.
func (e DocumentStatus) Valid() bool {
	switch e {
	case DocumentStatusFailed:
		return true
	case DocumentStatusPending:
		return true
	case DocumentStatusProcessing:
		return true
	case DocumentStatusReady:
		return true
	default:
		return false
	}
}

// Defines values for JobStatus.
const (
	JobStatusFailed    JobStatus = "failed"
	JobStatusQueued    JobStatus = "queued"
	JobStatusRunning   JobStatus = "running"
	JobStatusSucceeded JobStatus = "succeeded"
)

// Valid indicates whether the value is a known member of the JobStatus enum.
func (e JobStatus) Valid() bool {
	switch e {
	case JobStatusFailed:
		return true
	case JobStatusQueued:
		return true
	case JobStatusRunning:
		return true
	case JobStatusSucceeded:
		return true
	default:
		return false
	}
}

// Defines values for JobType.
const (
	Ingest JobType = "ingest"
)

// Valid indicates whether the value is a known member of the JobType enum.
func (e JobType) Valid() bool {
	switch e {
	case Ingest:
		return true
	default:
		return false
	}
}

// Defines values for QueryRequestTrace.
const (
	Full    QueryRequestTrace = "full"
	Summary QueryRequestTrace = "summary"
)

// Valid indicates whether the value is a known member of the QueryRequestTrace enum.
func (e QueryRequestTrace) Valid() bool {
	switch e {
	case Full:
		return true
	case Summary:
		return true
	default:
		return false
	}
}

// Defines values for TraceCache.
const (
	Bypass TraceCache = "bypass"
	Hit    TraceCache = "hit"
	Miss   TraceCache = "miss"
)

// Valid indicates whether the value is a known member of the TraceCache enum.
func (e TraceCache) Valid() bool {
	switch e {
	case Bypass:
		return true
	case Hit:
		return true
	case Miss:
		return true
	default:
		return false
	}
}

// Citation defines model for Citation.
type Citation struct {
	ChunkId    openapi_types.UUID `json:"chunk_id"`
	DocumentId openapi_types.UUID `json:"document_id"`

	// Excerpt Fragmento recuperado que sustenta la respuesta
	Excerpt *string `json:"excerpt,omitempty"`

	// Locator Ubicación dentro del documento
	//
	// Examples: considerando 7.3
	Locator *string `json:"locator,omitempty"`
	Score   float32 `json:"score"`

	// Source Nombre legible del documento
	//
	// Examples: RCA 042/2019
	Source string `json:"source"`
}

// Document defines model for Document.
type Document struct {
	ChunkCount *int                    `json:"chunk_count,omitempty"`
	Collection string                  `json:"collection"`
	CreatedAt  time.Time               `json:"created_at"`
	Id         openapi_types.UUID      `json:"id"`
	Metadata   *map[string]interface{} `json:"metadata,omitempty"`
	Source     string                  `json:"source"`
	Status     DocumentStatus          `json:"status"`
}

// DocumentStatus defines model for Document.Status.
type DocumentStatus string

// DocumentPage defines model for DocumentPage.
type DocumentPage struct {
	Data []Document `json:"data"`

	// NextCursor Nulo cuando no hay más páginas
	NextCursor *string `json:"next_cursor,omitempty"`
}

// Job defines model for Job.
type Job struct {
	CreatedAt time.Time          `json:"created_at"`
	Error     *string            `json:"error,omitempty"`
	Id        openapi_types.UUID `json:"id"`
	Progress  *int               `json:"progress,omitempty"`

	// ResourceId Documento resultante, una vez completado
	ResourceId *openapi_types.UUID `json:"resource_id,omitempty"`
	Status     JobStatus           `json:"status"`
	Type       JobType             `json:"type"`
}

// JobStatus defines model for Job.Status.
type JobStatus string

// JobType defines model for Job.Type.
type JobType string

// Problem Error conforme a RFC 9457
type Problem struct {
	Detail *string `json:"detail,omitempty"`
	Errors *[]struct {
		Field   *string `json:"field,omitempty"`
		Message *string `json:"message,omitempty"`
	} `json:"errors,omitempty"`
	Instance *string `json:"instance,omitempty"`
	Status   int     `json:"status"`
	Title    string  `json:"title"`
	TraceId  *string `json:"trace_id,omitempty"`

	// Type Examples: https://api.example.cl/problems/validation-error
	Type string `json:"type"`
}

// QueryRequest defines model for QueryRequest.
type QueryRequest struct {
	// Collection Restringe la búsqueda a una colección
	Collection *string `json:"collection,omitempty"`

	// Filters Filtros sobre los metadatos del documento
	Filters  *map[string]interface{} `json:"filters,omitempty"`
	Question string                  `json:"question"`
	TopK     *int                    `json:"top_k,omitempty"`
	Trace    *QueryRequestTrace      `json:"trace,omitempty"`
}

// QueryRequestTrace defines model for QueryRequest.Trace.
type QueryRequestTrace string

// QueryResponse defines model for QueryResponse.
type QueryResponse struct {
	Answer    string             `json:"answer"`
	Citations []Citation         `json:"citations"`
	QueryId   openapi_types.UUID `json:"query_id"`
	Trace     Trace              `json:"trace"`
}

// Trace defines model for Trace.
type Trace struct {
	Cache   TraceCache `json:"cache"`
	CostUsd *float32   `json:"cost_usd,omitempty"`

	// Degraded Verdadero si se respondió por fallback
	Degraded  *bool `json:"degraded,omitempty"`
	LatencyMs struct {
		Generation *int `json:"generation,omitempty"`
		Retrieval  *int `json:"retrieval,omitempty"`
		Total      *int `json:"total,omitempty"`
	} `json:"latency_ms"`
	Model string `json:"model"`

	// Provider Examples: ollama
	Provider string `json:"provider"`

	// Retrieved Solo presente con trace=full
	Retrieved *[]struct {
		ChunkId *openapi_types.UUID `json:"chunk_id,omitempty"`
		Rank    *int                `json:"rank,omitempty"`
		Score   *float32            `json:"score,omitempty"`
	} `json:"retrieved,omitempty"`
	Tokens *struct {
		Completion *int `json:"completion,omitempty"`
		Prompt     *int `json:"prompt,omitempty"`
	} `json:"tokens,omitempty"`

	// TraceId Identificador OpenTelemetry
	TraceId string `json:"trace_id"`
}

// TraceCache defines model for Trace.Cache.
type TraceCache string

// Usage defines model for Usage.
type Usage struct {
	ByProvider *[]struct {
		CostUsd  *float32 `json:"cost_usd,omitempty"`
		Provider *string  `json:"provider,omitempty"`
		Queries  *int     `json:"queries,omitempty"`
	} `json:"by_provider,omitempty"`
	CacheHitRate *float32            `json:"cache_hit_rate,omitempty"`
	CostUsd      *float32            `json:"cost_usd,omitempty"`
	PeriodEnd    *openapi_types.Date `json:"period_end,omitempty"`
	PeriodStart  *openapi_types.Date `json:"period_start,omitempty"`
	Queries      *int                `json:"queries,omitempty"`
	TokensTotal  *int                `json:"tokens_total,omitempty"`
}

// Cursor defines model for Cursor.
type Cursor = string

// IdempotencyKey defines model for IdempotencyKey.
type IdempotencyKey = string

// Limit defines model for Limit.
type Limit = int

// BadRequest Error conforme a RFC 9457
type BadRequest = Problem

// Conflict Error conforme a RFC 9457
type Conflict = Problem

// NotFound Error conforme a RFC 9457
type NotFound = Problem

// ServiceUnavailable Error conforme a RFC 9457
type ServiceUnavailable = Problem

// TooManyRequests Error conforme a RFC 9457
type TooManyRequests = Problem

// Unauthorized Error conforme a RFC 9457
type Unauthorized = Problem

// ListDocumentsParams defines parameters for ListDocuments.
type ListDocumentsParams struct {
	// Cursor Cursor opaco devuelto en la página anterior
	Cursor     *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`
	Limit      *Limit  `form:"limit,omitempty" json:"limit,omitempty"`
	Collection *string `form:"collection,omitempty" json:"collection,omitempty"`
}

// CreateDocumentMultipartBody defines parameters for CreateDocument.
type CreateDocumentMultipartBody struct {
	// Collection Examples: rca
	Collection string             `json:"collection"`
	File       openapi_types.File `json:"file"`

	// Metadata JSON con metadatos libres del documento
	Metadata *string `json:"metadata,omitempty"`
}

// CreateDocumentParams defines parameters for CreateDocument.
type CreateDocumentParams struct {
	// IdempotencyKey Clave única del cliente. Reintentos con la misma clave devuelven
	// la respuesta original en lugar de ejecutar la operación de nuevo.
	IdempotencyKey *IdempotencyKey `json:"Idempotency-Key,omitempty"`
}

// CreateQueryParams defines parameters for CreateQuery.
type CreateQueryParams struct {
	// IdempotencyKey Clave única del cliente. Reintentos con la misma clave devuelven
	// la respuesta original en lugar de ejecutar la operación de nuevo.
	IdempotencyKey *IdempotencyKey `json:"Idempotency-Key,omitempty"`
}

// GetUsageParams defines parameters for GetUsage.
type GetUsageParams struct {
	From *openapi_types.Date `form:"from,omitempty" json:"from,omitempty"`
	To   *openapi_types.Date `form:"to,omitempty" json:"to,omitempty"`
}

// CreateDocumentMultipartRequestBody defines body for CreateDocument for multipart/form-data ContentType.
type CreateDocumentMultipartRequestBody CreateDocumentMultipartBody

// CreateQueryJSONRequestBody defines body for CreateQuery for application/json ContentType.
type CreateQueryJSONRequestBody = QueryRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// ListDocuments Lista documentos del corpus
	// (GET /documents)
	ListDocuments(w http.ResponseWriter, r *http.Request, params ListDocumentsParams)
	// CreateDocument Registra un documento para ingesta
	// (POST /documents)
	CreateDocument(w http.ResponseWriter, r *http.Request, params CreateDocumentParams)
	// DeleteDocument Elimina un documento y sus chunks
	// (DELETE /documents/{documentId})
	DeleteDocument(w http.ResponseWriter, r *http.Request, documentId openapi_types.UUID)
	// GetDocument Obtiene un documento
	// (GET /documents/{documentId})
	GetDocument(w http.ResponseWriter, r *http.Request, documentId openapi_types.UUID)
	// GetJob Consulta el estado de un trabajo asíncrono
	// (GET /jobs/{jobId})
	GetJob(w http.ResponseWriter, r *http.Request, jobId openapi_types.UUID)
	// CreateQuery Ejecuta una consulta semántica
	// (POST /queries)
	CreateQuery(w http.ResponseWriter, r *http.Request, params CreateQueryParams)
	// GetUsage Consumo agregado del periodo
	// (GET /usage)
	GetUsage(w http.ResponseWriter, r *http.Request, params GetUsageParams)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListDocuments operation middleware
func (siw *ServerInterfaceWrapper) ListDocuments(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListDocumentsParams

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cursor", r.URL.Query(), &params.Cursor, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "cursor"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cursor", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "collection" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "collection", r.URL.Query(), &params.Collection, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "collection"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "collection", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListDocuments(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateDocument operation middleware
func (siw *ServerInterfaceWrapper) CreateDocument(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params CreateDocumentParams

	headers := r.Header

	// ------------- Optional header parameter "Idempotency-Key" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Idempotency-Key")]; found {
		var IdempotencyKey IdempotencyKey
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Idempotency-Key", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Idempotency-Key", valueList[0], &IdempotencyKey, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Idempotency-Key", Err: err})
			return
		}

		params.IdempotencyKey = &IdempotencyKey

	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateDocument(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteDocument operation middleware
func (siw *ServerInterfaceWrapper) DeleteDocument(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "documentId" -------------
	var documentId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "documentId", r.PathValue("documentId"), &documentId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "documentId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteDocument(w, r, documentId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetDocument operation middleware
func (siw *ServerInterfaceWrapper) GetDocument(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "documentId" -------------
	var documentId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "documentId", r.PathValue("documentId"), &documentId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "documentId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetDocument(w, r, documentId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetJob operation middleware
func (siw *ServerInterfaceWrapper) GetJob(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "jobId" -------------
	var jobId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "jobId", r.PathValue("jobId"), &jobId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "jobId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetJob(w, r, jobId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateQuery operation middleware
func (siw *ServerInterfaceWrapper) CreateQuery(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params CreateQueryParams

	headers := r.Header

	// ------------- Optional header parameter "Idempotency-Key" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Idempotency-Key")]; found {
		var IdempotencyKey IdempotencyKey
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Idempotency-Key", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Idempotency-Key", valueList[0], &IdempotencyKey, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Idempotency-Key", Err: err})
			return
		}

		params.IdempotencyKey = &IdempotencyKey

	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateQuery(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetUsage operation middleware
func (siw *ServerInterfaceWrapper) GetUsage(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params GetUsageParams

	// ------------- Optional query parameter "from" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "from", r.URL.Query(), &params.From, runtime.BindQueryParameterOptions{Type: "string", Format: "date"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "from"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "from", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "to" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "to", r.URL.Query(), &params.To, runtime.BindQueryParameterOptions{Type: "string", Format: "date"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "to"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "to", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetUsage(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/queries", wrapper.CreateQuery)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/documents", wrapper.ListDocuments)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/documents", wrapper.CreateDocument)
	m.HandleFunc(http.MethodDelete+" "+options.BaseURL+"/documents/{documentId}", wrapper.DeleteDocument)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/documents/{documentId}", wrapper.GetDocument)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/jobs/{jobId}", wrapper.GetJob)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/usage", wrapper.GetUsage)

	return m
}

type BadRequestApplicationProblemPlusJSONResponse Problem

type ConflictApplicationProblemPlusJSONResponse Problem

type NotFoundApplicationProblemPlusJSONResponse Problem

type ServiceUnavailableApplicationProblemPlusJSONResponse Problem

type TooManyRequestsResponseHeaders struct {
	RetryAfter *int
}
type TooManyRequestsApplicationProblemPlusJSONResponse struct {
	Body Problem

	Headers TooManyRequestsResponseHeaders
}

type UnauthorizedApplicationProblemPlusJSONResponse Problem

type ListDocumentsRequestObject struct {
	Params ListDocumentsParams
}

type ListDocumentsResponseObject interface {
	VisitListDocumentsResponse(w http.ResponseWriter) error
}

type ListDocuments200JSONResponse DocumentPage

func (response ListDocuments200JSONResponse) VisitListDocumentsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListDocuments401ApplicationProblemPlusJSONResponse struct {
	UnauthorizedApplicationProblemPlusJSONResponse
}

func (response ListDocuments401ApplicationProblemPlusJSONResponse) VisitListDocumentsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type CreateDocumentRequestObject struct {
	Params CreateDocumentParams
	Body   *multipart.Reader
}

type CreateDocumentResponseObject interface {
	VisitCreateDocumentResponse(w http.ResponseWriter) error
}

type CreateDocument202ResponseHeaders struct {
	Location *string
}

type CreateDocument202JSONResponse struct {
	Body    Job
	Headers CreateDocument202ResponseHeaders
}

func (response CreateDocument202JSONResponse) VisitCreateDocumentResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.Location != nil {
		w.Header().Set("Location", fmt.Sprint(*response.Headers.Location))
	}
	w.WriteHeader(202)
	_, err := buf.WriteTo(w)
	return err
}

type CreateDocument400ApplicationProblemPlusJSONResponse struct {
	BadRequestApplicationProblemPlusJSONResponse
}

func (response CreateDocument400ApplicationProblemPlusJSONResponse) VisitCreateDocumentResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type CreateDocument409ApplicationProblemPlusJSONResponse struct {
	ConflictApplicationProblemPlusJSONResponse
}

func (response CreateDocument409ApplicationProblemPlusJSONResponse) VisitCreateDocumentResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type CreateDocument413ApplicationProblemPlusJSONResponse Problem

func (response CreateDocument413ApplicationProblemPlusJSONResponse) VisitCreateDocumentResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(413)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteDocumentRequestObject struct {
	DocumentId openapi_types.UUID `json:"documentId"`
}

type DeleteDocumentResponseObject interface {
	VisitDeleteDocumentResponse(w http.ResponseWriter) error
}

type DeleteDocument204Response struct {
}

func (response DeleteDocument204Response) VisitDeleteDocumentResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteDocument404ApplicationProblemPlusJSONResponse struct {
	NotFoundApplicationProblemPlusJSONResponse
}

func (response DeleteDocument404ApplicationProblemPlusJSONResponse) VisitDeleteDocumentResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetDocumentRequestObject struct {
	DocumentId openapi_types.UUID `json:"documentId"`
}

type GetDocumentResponseObject interface {
	VisitGetDocumentResponse(w http.ResponseWriter) error
}

type GetDocument200JSONResponse Document

func (response GetDocument200JSONResponse) VisitGetDocumentResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetDocument404ApplicationProblemPlusJSONResponse struct {
	NotFoundApplicationProblemPlusJSONResponse
}

func (response GetDocument404ApplicationProblemPlusJSONResponse) VisitGetDocumentResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetJobRequestObject struct {
	JobId openapi_types.UUID `json:"jobId"`
}

type GetJobResponseObject interface {
	VisitGetJobResponse(w http.ResponseWriter) error
}

type GetJob200JSONResponse Job

func (response GetJob200JSONResponse) VisitGetJobResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetJob404ApplicationProblemPlusJSONResponse struct {
	NotFoundApplicationProblemPlusJSONResponse
}

func (response GetJob404ApplicationProblemPlusJSONResponse) VisitGetJobResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type CreateQueryRequestObject struct {
	Params CreateQueryParams
	Body   *CreateQueryJSONRequestBody
}

type CreateQueryResponseObject interface {
	VisitCreateQueryResponse(w http.ResponseWriter) error
}

type CreateQuery200ResponseHeaders struct {
	XRateLimitRemaining *int
	XTraceId            *string
}

type CreateQuery200JSONResponse struct {
	Body    QueryResponse
	Headers CreateQuery200ResponseHeaders
}

func (response CreateQuery200JSONResponse) VisitCreateQueryResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.XRateLimitRemaining != nil {
		w.Header().Set("X-RateLimit-Remaining", fmt.Sprint(*response.Headers.XRateLimitRemaining))
	}
	if response.Headers.XTraceId != nil {
		w.Header().Set("X-Trace-Id", fmt.Sprint(*response.Headers.XTraceId))
	}
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type CreateQuery400ApplicationProblemPlusJSONResponse struct {
	BadRequestApplicationProblemPlusJSONResponse
}

func (response CreateQuery400ApplicationProblemPlusJSONResponse) VisitCreateQueryResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type CreateQuery401ApplicationProblemPlusJSONResponse struct {
	UnauthorizedApplicationProblemPlusJSONResponse
}

func (response CreateQuery401ApplicationProblemPlusJSONResponse) VisitCreateQueryResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type CreateQuery429ApplicationProblemPlusJSONResponse struct {
	TooManyRequestsApplicationProblemPlusJSONResponse
}

func (response CreateQuery429ApplicationProblemPlusJSONResponse) VisitCreateQueryResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	if response.Headers.RetryAfter != nil {
		w.Header().Set("Retry-After", fmt.Sprint(*response.Headers.RetryAfter))
	}
	w.WriteHeader(429)
	_, err := buf.WriteTo(w)
	return err
}

type CreateQuery503ApplicationProblemPlusJSONResponse struct {
	ServiceUnavailableApplicationProblemPlusJSONResponse
}

func (response CreateQuery503ApplicationProblemPlusJSONResponse) VisitCreateQueryResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

type GetUsageRequestObject struct {
	Params GetUsageParams
}

type GetUsageResponseObject interface {
	VisitGetUsageResponse(w http.ResponseWriter) error
}

type GetUsage200JSONResponse Usage

func (response GetUsage200JSONResponse) VisitGetUsageResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// ListDocuments Lista documentos del corpus
	// (GET /documents)
	ListDocuments(ctx context.Context, request ListDocumentsRequestObject) (ListDocumentsResponseObject, error)
	// CreateDocument Registra un documento para ingesta
	// (POST /documents)
	CreateDocument(ctx context.Context, request CreateDocumentRequestObject) (CreateDocumentResponseObject, error)
	// DeleteDocument Elimina un documento y sus chunks
	// (DELETE /documents/{documentId})
	DeleteDocument(ctx context.Context, request DeleteDocumentRequestObject) (DeleteDocumentResponseObject, error)
	// GetDocument Obtiene un documento
	// (GET /documents/{documentId})
	GetDocument(ctx context.Context, request GetDocumentRequestObject) (GetDocumentResponseObject, error)
	// GetJob Consulta el estado de un trabajo asíncrono
	// (GET /jobs/{jobId})
	GetJob(ctx context.Context, request GetJobRequestObject) (GetJobResponseObject, error)
	// CreateQuery Ejecuta una consulta semántica
	// (POST /queries)
	CreateQuery(ctx context.Context, request CreateQueryRequestObject) (CreateQueryResponseObject, error)
	// GetUsage Consumo agregado del periodo
	// (GET /usage)
	GetUsage(ctx context.Context, request GetUsageRequestObject) (GetUsageResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// ListDocuments operation middleware
func (sh *strictHandler) ListDocuments(w http.ResponseWriter, r *http.Request, params ListDocumentsParams) {
	var request ListDocumentsRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListDocuments(ctx, request.(ListDocumentsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListDocuments")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListDocumentsResponseObject); ok {
		if err := validResponse.VisitListDocumentsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateDocument operation middleware
func (sh *strictHandler) CreateDocument(w http.ResponseWriter, r *http.Request, params CreateDocumentParams) {
	var request CreateDocumentRequestObject

	request.Params = params

	if reader, err := r.MultipartReader(); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode multipart body: %w", err))
		return
	} else {
		request.Body = reader
	}

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateDocument(ctx, request.(CreateDocumentRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateDocument")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateDocumentResponseObject); ok {
		if err := validResponse.VisitCreateDocumentResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteDocument operation middleware
func (sh *strictHandler) DeleteDocument(w http.ResponseWriter, r *http.Request, documentId openapi_types.UUID) {
	var request DeleteDocumentRequestObject

	request.DocumentId = documentId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteDocument(ctx, request.(DeleteDocumentRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteDocument")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteDocumentResponseObject); ok {
		if err := validResponse.VisitDeleteDocumentResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetDocument operation middleware
func (sh *strictHandler) GetDocument(w http.ResponseWriter, r *http.Request, documentId openapi_types.UUID) {
	var request GetDocumentRequestObject

	request.DocumentId = documentId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetDocument(ctx, request.(GetDocumentRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetDocument")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetDocumentResponseObject); ok {
		if err := validResponse.VisitGetDocumentResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetJob operation middleware
func (sh *strictHandler) GetJob(w http.ResponseWriter, r *http.Request, jobId openapi_types.UUID) {
	var request GetJobRequestObject

	request.JobId = jobId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetJob(ctx, request.(GetJobRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetJob")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetJobResponseObject); ok {
		if err := validResponse.VisitGetJobResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateQuery operation middleware
func (sh *strictHandler) CreateQuery(w http.ResponseWriter, r *http.Request, params CreateQueryParams) {
	var request CreateQueryRequestObject

	request.Params = params

	var body CreateQueryJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateQuery(ctx, request.(CreateQueryRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateQuery")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateQueryResponseObject); ok {
		if err := validResponse.VisitCreateQueryResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetUsage operation middleware
func (sh *strictHandler) GetUsage(w http.ResponseWriter, r *http.Request, params GetUsageParams) {
	var request GetUsageRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetUsage(ctx, request.(GetUsageRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetUsage")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetUsageResponseObject); ok {
		if err := validResponse.VisitGetUsageResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"vFrNchu3sn4V1Ny7uyORkp1Kwqq7cBz7lnwVx5Htc1Jlq1RNoElBxgBj/PCYUfFh/ABZnMouW73YqQZm",
	"ODMkKFL58Y7kDIDu/rq//gFvC26q2mjU3hWT26IGCxV6tPHb02CdsfRJoONW1l4aXUya35mpgRsmcBFQ",
	"ecNQMwWsvvs8lxoYaI9WGluUhaQ1HwPaZVEWGiosJgVPW5eF49dYAZ3hlzU9cd5KPS9Wq7I4E1jVxqPm",
	"y//HZUYOBQtkd79ryYEJVIwridrjMbtAqT1qbxzjJspVSVcB43FFEnmB+r1WwCy6OqDzwIyVJLuKqoQ5",
	"WCaQ4Q3y4MHSJqZGC1ze/abpiQ64MMfvdaviNYJA2+nYE/+I5O8rW8Gnc9Rzf11MTk6/KTPKn8tKeno1",
	"Zz4VH/Y3FDiDoHwxOR2XtLusQlVMTsb0Term2/ocss4cbbGik8gARjuMmH8H4gI/kj3oGzfRjPQR6lpJ",
	"DmT6UW3NVGH1PzeOcLjtifHfFmfFpPivUedXo/TUjV6lVenQIZKvjZJc+iCY1Iu7z0oKKFZl8dTomZL8",
	"i4rSnmmi56Bi5BrCMOA+gIpuZjG6L0n40vjnJmjxJSW8SMczTTFHh1oQUZjXaBeS41sNC5AKpgq/KIZS",
	"s9qaBaIwMXLmqLtwkeRjkkRalcUbY34AvWwczX1JKc/vfq2kJw5grnU6dAw/cRRSmKJswjgKdYHeLo+e",
	"zDza4eHbYbQqi7cagr82Vv6CX9QfnloUqLkEhY5BcESBjpkulFwklGanSOzSQ1p8W9SWWM3LFP78OugP",
	"VzLKPzO2Al9MihCkKLY4qiyE4aFC7Q99n4xsa79N5M8tzGkjE0OLSFYY9jEgc8GRCYH1eTq3tTIcfC5X",
	"vZ1KvqZs7a2JEdxKTnjjJ6hqReq/I8icFGhBC8O+Pn5UXGbOctxYHCg8UwaIjjve7bHueL2FDtWUvKUs",
	"nAmW47a0L001tcgUzilU7hX14ukTNn58Ojodn3ybETPy+scgLfniuw7XIWprSVqtuo3M9Aa5J2G/bxbs",
	"8hZuQnq4GRVlwY1SyFtX27IktwgexRX4gTkFeDzyssIc0gf6WoUeBPgYVyCEJBlAveqJ723AjLYdNNvA",
	"e/AhKo6akH1X1KgFPSzJMBydS18sgqBsPQOpUOxHZ4hEz2jrMwe2ug+kVzDHbaBaS0iPldtHNWu8V+tz",
	"wFpY0neNn/wV31EXvgzKMB5i8GjDrmHJqrvPrq0J3Rqnd60hykIHpYrLTYNEeXNqvjDTjBv+ATdCa5MK",
	"uyQ62NNqa+YWnWvKulzhNS4zsWExId6w59CULQbEiC4oT+V0yYIGtsBfGIGmyMGJFPYKuO22HwMGpHdt",
	"0Dpp7QLniCL+utNt2x+6naSeU6l4mIfHVw536TblbRnnGWFH5RmpjgzYxfOn7NvHX32d4rDv9+hBqmww",
	"Rwdwg6AYrp1JVCK7tELnmjDb1npLjc0Qktp50HspZtthvPQqv8pbWPvRbsh6yePa+9pNRiOo5XHz+zFX",
	"bWniRguguoHMfZQC5bLvZ1YW+/BuoE4ir9XKofwTdTa9lmMjtAcJZLMOTocjVQfTu9/dx4ACGMQw4UYh",
	"j3k/FxIzqdom977ksFGlSOWtccyZmKONY02SMW4rU2+pGfVr1Og1f6fjhijaHx7lgs7UVx8GTd5XvVrj",
	"dE+L17jHYH3hQlVB7CjbSO5+mUUC3IfwWqF7QE195TaqoN2/0OZLgqY0dQenq3Uxm4m12DYfWp6uzXTf",
	"aW/iSxljpHPKVre+Ju3WOUu9aQ/d8Hvg1wOivY79fiUdbTdd1uBclqC5cf4qOJGtT7fqUIFzCwLFwDlm",
	"oNyW8/8DraC+yDAnmUOWhgZC3v3GamPZDJSaAv/QHTI1RiFEVBTEIchVjmVTk7hRIQ6ypLcSF6B2cKLx",
	"+Uc5Jq6MwHwyoL6V6v5NnjRKQQVZQzeCYSZ5vzbKsNpi7MTiGCHi/78xsMpd+eZBrZcF/SFvkd3dyQb6",
	"h+Qqbz6gzsmaCpCdqNXWVLU/FJd++hpa8ox6NjmTHISx7Mca9RtUWFFbvj8Ftbv24G19oGwCbOCbufB8",
	"67L19HR51XeZXYg+KBb7G27hTQTT7HqQRTdwjNpeXUt/ZcHjYfI8UHq00ogr1GKrBs8Wzel158H6gxbc",
	"Y4DWTa8eQAYUKMiDlX75mpi9gRXBon0SKBG33563kr3455t24hr5LT7tRKWSKk1npJ6ZbVd+8uqMicgG",
	"sZ5nDqu7z9pLDk1BwY2tg1tXEaDQlZE8enO091pgNwhxDJx0XgqIHHx+/gNbEtX8AlNJ9ZugAxWwWYhT",
	"8ff6vX5jRH/inbYWwKTmKizpbccocTkGvYImTsZRsyWVVu91PGI9G0/DFRJ0Pf0juZ03bMlSeElIY3Il",
	"OTYFQTPI/uHsTa+0LV4p8BB9YWCrziZFWSzQumTSk+Px8ZiWmxo11LKYFI+OT47HFPHgryOko3Ztk22i",
	"t8U5PuFyJopJcS6d/379Vjm4BHmXrwa6V0bNJcmq3PtmmujTi9kbkUHXv/NW5HJjXn86Ht8za3zYjHEw",
	"Q8gMGl81dzsCO9dwZP/H45Nde6+FHQ3GozEAm4ozIQC9PdNlTowHCjCYx2TcIUndeW1cZpL4THOjgPWr",
	"cUYQsJhdpZ6z5XAujQyrKQoh9dwdv9fPFEuTHKhkXIwUZHe/am6NNhMWHNLmN2baXXzF/R3Og7T0DBbU",
	"3SWHHzra09jvrscrD/W0jeuw5AqxDP/OiOWGF1RBeVmD9SMKp6N2ANQ5wn19Vr8Esjxf/8ykGiaSqdSQ",
	"S8vDWdwQrhevf3wZqaPrpJScWtzZUO3I9VGYweRsO5kP11CDt9qKpdO/LJZemGkuhLq5DnCs48VSdJ+B",
	"0w0vIc4Nh3wD/PbiPNopeSNLsxgY0Meepn0Vg3e8P3h714Jxybf7l6wv72jByaMveSPyxPJruTDpVicG",
	"rIcK7v5tWHX3+ZOszAb/XOBcOm+BBb3JG51RczS0KnsJZnTbfjwTq4SWwlRtDXng+/h7jwc2vPBxhteU",
	"rKRu7vkepzfuN//6ZnKoarPRUNMlc8ElitxNuNnc+X/od+vx12eme0Pqz5rmx6mXqHFgmt3pZ0jdMaNT",
	"0dEl9M4Zik3iyUdottVb0WGjGzN1o9sbM208axcWxDp/Iww7SO1ZuiEnKvIWpnDzp6F42lZ+3f27iMA0",
	"+/dycg8hstKB4ERT/nlcel1JW4/kUv5PTan3N+b7Pw7qYAB7UJYc/9VnN3PC7H8dNluVYXL8+egCPMbK",
	"+ugCK5DxOuP+u/qy+Pkojt2OzvaOHASyptuhBCGnQQq4tz7/wxn1wRV0WTw+PSANb/7XYlUWX40f7V+X",
	"+TPJRiZJf4xqpu1bXW0vLtsoSfkytCOVXSSWZi75KN5ommbWVPl6Jz9H2NV8RaI/fJe/swlL2uf/mORC",
	"lWg2jU9MjjUrw2Bucd4ycvtqB0cC4HLVH4JEC/fHH+8uSUuHdtHaf6MXtEaE9QVLsKoZgWRulRYnsend",
	"+B+O4bGb71ZORiNFP14b5yffjL8Zx4WXa7lvc/ZQHlzP6VwHaet020efpZIudoLON21gr9/cyN+5LdYZ",
	"r01I/S7RDdJMbnkL1DLNSXoLEjary9V/AgAA//8=",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
